package com.jbangit.unimini

import android.net.Uri
import java.io.File

/**
 * 文件mimeType和扩展名相关
 */
object MimeTypes {
    private var mimeTypeAndSuffix: Map<String, String> = mapOf(
        "application/andrew-inset" to "ez",
        "application/dsptype" to "tsp",
        "application/futuresplash" to "spl",
        "application/hta" to "hta",
        "application/mac-binhex40" to "hqx",
        "application/mac-compactpro" to "cpt",
        "application/mathematica" to "nb",
        "application/msaccess" to "mdb",
        "application/oda" to "oda",
        "application/ogg" to "ogg",
        "application/pdf" to "pdf",
        "application/pgp-keys" to "key",
        "application/pgp-signature" to "pgp",
        "application/pics-rules" to "prf",
        "application/rar" to "rar",
        "application/rdf+xml" to "rdf",
        "application/rss+xml" to "rss",
        "application/zip" to "zip",
        "application/vnd.android.package-archive" to "apk",
        "application/vnd.cinderella" to "cdy",
        "application/vnd.ms-pki.stl" to "stl",
        "application/msword" to "doc",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document" to "docx",
        "application/vnd.ms-excel application/x-excel" to "xls",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to "xlsx",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation" to "pptx",
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow" to "ppsx",
        "application/vnd.oasis.opendocument.database" to "odb",
        "application/vnd.oasis.opendocument.formula" to "odf",
        "application/vnd.oasis.opendocument.graphics" to "odg",
        "application/vnd.oasis.opendocument.graphics-template" to "otg",
        "application/vnd.oasis.opendocument.image" to "odi",
        "application/vnd.oasis.opendocument.spreadsheet" to "ods",
        "application/vnd.oasis.opendocument.spreadsheet-template" to "ots",
        "application/vnd.oasis.opendocument.text" to "odt",
        "application/vnd.oasis.opendocument.text-master" to "odm",
        "application/vnd.oasis.opendocument.text-template" to "ott",
        "application/vnd.oasis.opendocument.text-web" to "oth",
        "application/vnd.rim.cod" to "cod",
        "application/vnd.smaf" to "mmf",
        "application/vnd.stardivision.calc" to "sdc",
        "application/vnd.stardivision.draw" to "sda",
        "application/vnd.stardivision.impress" to "sdd",
        "application/vnd.stardivision.impress" to "sdp",
        "application/vnd.stardivision.math" to "smf",
        "application/vnd.stardivision.writer" to "sdw",
        "application/vnd.stardivision.writer" to "vor",
        "application/vnd.stardivision.writer-global" to "sgl",
        "application/vnd.sun.xml.calc" to "sxc",
        "application/vnd.sun.xml.calc.template" to "stc",
        "application/vnd.sun.xml.draw" to "sxd",
        "application/vnd.sun.xml.draw.template" to "std",
        "application/vnd.sun.xml.impress" to "sxi",
        "application/vnd.sun.xml.impress.template" to "sti",
        "application/vnd.sun.xml.math" to "sxm",
        "application/vnd.sun.xml.writer" to "sxw",
        "application/vnd.sun.xml.writer.global" to "sxg",
        "application/vnd.sun.xml.writer.template" to "stw",
        "application/vnd.visio" to "vsd",
        "application/x-abiword" to "abw",
        "application/x-apple-diskimage" to "dmg",
        "application/x-bcpio" to "bcpio",
        "application/x-bittorrent" to "torrent",
        "application/x-cdf" to "cdf",
        "application/x-cdlink" to "vcd",
        "application/x-chess-pgn" to "pgn",
        "application/x-cpio" to "cpio",
        "application/x-debian-package" to "deb",
        "application/x-debian-package" to "udeb",
        "application/x-director" to "dcr",
        "application/x-director" to "dir",
        "application/x-director" to "dxr",
        "application/x-dms" to "dms",
        "application/x-doom" to "wad",
        "application/x-dvi" to "dvi",
        "application/x-flac" to "flac",
        "application/x-font" to "pfa",
        "application/x-font" to "pfb",
        "application/x-font" to "gsf",
        "application/x-font" to "pcf",
        "application/x-font" to "pcf.Z",
        "application/x-freemind" to "mm",
        "application/x-futuresplash" to "spl",
        "application/x-gnumeric" to "gnumeric",
        "application/x-go-sgf" to "sgf",
        "application/x-graphing-calculator" to "gcf",
        "application/x-gtar" to "gtar",
        "application/x-gtar" to "tgz",
        "application/x-gtar" to "taz",
        "application/x-hdf" to "hdf",
        "application/x-ica" to "ica",
        "application/x-internet-signup" to "ins",
        "application/x-internet-signup" to "isp",
        "application/x-iphone" to "iii",
        "application/x-iso9660-image" to "iso",
        "application/x-jmol" to "jmz",
        "application/x-kchart" to "chrt",
        "application/x-killustrator" to "kil",
        "application/x-koan" to "skp",
        "application/x-koan" to "skd",
        "application/x-koan" to "skt",
        "application/x-koan" to "skm",
        "application/x-kpresenter" to "kpr",
        "application/x-kpresenter" to "kpt",
        "application/x-kspread" to "ksp",
        "application/x-kword" to "kwd",
        "application/x-kword" to "kwt",
        "application/x-latex" to "latex",
        "application/x-lha" to "lha",
        "application/x-lzh" to "lzh",
        "application/x-lzx" to "lzx",
        "application/x-maker" to "frm",
        "application/x-maker" to "maker",
        "application/x-maker" to "frame",
        "application/x-maker" to "fb",
        "application/x-maker" to "book",
        "application/x-maker" to "fbdoc",
        "application/x-mif" to "mif",
        "application/x-ms-wmd" to "wmd",
        "application/x-ms-wmz" to "wmz",
        "application/x-msi" to "msi",
        "application/x-ns-proxy-autoconfig" to "pac",
        "application/x-nwc" to "nwc",
        "application/x-object" to "o",
        "application/x-oz-application" to "oza",
        "application/x-pkcs7-certreqresp" to "p7r",
        "application/x-pkcs7-crl" to "crl",
        "application/x-quicktimeplayer" to "qtl",
        "application/x-shar" to "shar",
        "application/x-stuffit" to "sit",
        "application/x-sv4cpio" to "sv4cpio",
        "application/x-sv4crc" to "sv4crc",
        "application/x-tar" to "tar",
        "application/x-texinfo" to "texinfo",
        "application/x-texinfo" to "texi",
        "application/x-troff" to "t",
        "application/x-troff" to "roff",
        "application/x-troff-man" to "man",
        "application/x-ustar" to "ustar",
        "application/x-wais-source" to "src",
        "application/x-wingz" to "wz",
        "application/x-webarchive" to "webarchive",
        "application/x-x509-ca-cert" to "crt",
        "application/x-xcf" to "xcf",
        "application/x-xfig" to "fig",
        "audio/basic" to "snd",
        "audio/midi" to "mid",
        "audio/midi" to "midi",
        "audio/midi" to "kar",
        "audio/mpeg" to "mpga",
        "audio/mpeg" to "mpega",
        "audio/mpeg" to "mp2",
        "audio/mpeg" to "mp3",
        "audio/mpeg" to "m4a",
        "audio/mpegurl" to "m3u",
        "audio/prs.sid" to "sid",
        "audio/x-aiff" to "aif",
        "audio/x-aiff" to "aiff",
        "audio/x-aiff" to "aifc",
        "audio/x-gsm" to "gsm",
        "audio/x-mpegurl" to "m3u",
        "audio/x-ms-wma" to "wma",
        "audio/x-ms-wax" to "wax",
        "audio/x-pn-realaudio" to "ra",
        "audio/x-pn-realaudio" to "rm",
        "audio/x-pn-realaudio" to "ram",
        "audio/x-realaudio" to "ra",
        "audio/x-scpls" to "pls",
        "audio/x-sd2" to "sd2",
        "audio/x-wav" to "wav",
        "image/bmp" to "bmp",
        "image/gif" to "gif",
        "image/ico" to "ico",
        "image/ief" to "ief",
        "image/jpeg" to "jpg",
        "image/pcx" to "pcx",
        "image/png" to "png",
        "image/svg+xml" to "svg",
        "image/svg+xml" to "svgz",
        "image/tiff" to "tif",
        "image/vnd.djvu" to "djv",
        "image/vnd.wap.wbmp" to "wbmp",
        "image/x-cmu-raster" to "ras",
        "image/x-coreldraw" to "cdr",
        "image/x-coreldrawpattern" to "pat",
        "image/x-coreldrawtemplate" to "cdt",
        "image/x-corelphotopaint" to "cpt",
        "image/x-icon" to "ico",
        "image/x-jg" to "art",
        "image/x-jng" to "jng",
        "image/x-ms-bmp" to "bmp",
        "image/x-photoshop" to "psd",
        "image/x-portable-anymap" to "pnm",
        "image/x-portable-bitmap" to "pbm",
        "image/x-portable-graymap" to "pgm",
        "image/x-portable-pixmap" to "ppm",
        "image/x-rgb" to "rgb",
        "image/x-xbitmap" to "xbm",
        "image/x-xwindowdump" to "xwd",
        "model/iges" to "igs",
        "model/iges" to "iges",
        "model/mesh" to "msh",
        "model/mesh" to "mesh",
        "model/mesh" to "silo",
        "text/calendar" to "ics",
        "text/calendar" to "icz",
        "text/comma-separated-values" to "csv",
        "text/css" to "css",
        "text/h323" to "323",
        "text/iuls" to "uls",
        "text/mathml" to "mml",
        "text/plain" to "txt",
        "text/richtext" to "rtx",
        "text/rtf" to "rtf",
        "text/texmacs" to "ts",
        "text/text" to "phps",

        "text/html" to "html",
        "text/javascript" to "js",
        "text/xml" to "xml",

        "text/tab-separated-values" to "tsv",
        "text/x-bibtex" to "bib",
        "text/x-boo" to "boo",
        "text/x-c++hdr" to "h++",
        "text/x-c++hdr" to "hpp",
        "text/x-c++hdr" to "hxx",
        "text/x-c++hdr" to "hh",
        "text/x-c++src" to "c++",
        "text/x-c++src" to "cpp",
        "text/x-c++src" to "cxx",
        "text/x-chdr" to "h",
        "text/x-component" to "htc",
        "text/x-csh" to "csh",
        "text/x-csrc" to "c",
        "text/x-dsrc" to "d",
        "text/x-haskell" to "hs",
        "text/x-java" to "java",
        "text/x-literate-haskell" to "lhs",
        "text/x-moc" to "moc",
        "text/x-pascal" to "p",
        "text/x-pascal" to "pas",
        "text/x-pcs-gcd" to "gcd",
        "text/x-setext" to "etx",
        "text/x-tcl" to "tcl",
        "text/x-tex" to "tex",
        "text/x-tex" to "ltx",
        "text/x-tex" to "sty",
        "text/x-tex" to "cls",
        "text/x-vcalendar" to "vcs",
        "text/x-vcard" to "vcf",
        "video/3gpp" to "3gp",
        "video/3gpp" to "3g2",
        "video/dl" to "dl",
        "video/dv" to "dif",
        "video/dv" to "dv",
        "video/fli" to "fli",
        "video/mpeg" to "mpeg",
        "video/mpeg" to "mpg",
        "video/mpeg" to "mpe",
        "video/mp4" to "mp4",
        "video/mpeg" to "VOB",
        "video/quicktime" to "qt",
        "video/quicktime" to "mov",
        "video/vnd.mpegurl" to "mxu",
        "video/x-la-asf" to "lsf",
        "video/x-la-asf" to "lsx",
        "video/x-mng" to "mng",
        "video/x-ms-asf" to "asf",
        "video/x-ms-asf" to "asx",
        "video/x-ms-wm" to "wm",
        "video/x-ms-wmv" to "wmv",
        "video/x-ms-wmx" to "wmx",
        "video/x-ms-wvx" to "wvx",
        "video/x-msvideo" to "avi",
        "video/x-sgi-movie" to "movie",
        "x-conference/x-cooltalk" to "ice",
        "x-epoc/x-sisx-app" to "sisx"
    )
    private var suffixAntMiniType: Map<String, String> = mapOf(
        ".ez" to "application/andrew-inset",
        ".tsp" to "application/dsptype",
        ".spl" to "application/futuresplash",
        ".hta" to "application/hta",
        ".hqx" to "application/mac-binhex40",
        ".cpt" to "application/mac-compactpro",
        ".nb" to "application/mathematica",
        ".mdb" to "application/msaccess",
        ".oda" to "application/oda",
        ".ogg" to "application/ogg",
        ".pdf" to "application/pdf",
        ".key" to "application/pgp-keys",
        ".pgp" to "application/pgp-signature",
        ".prf" to "application/pics-rules",
        ".rar" to "application/rar",
        ".rdf" to "application/rdf+xml",
        ".rss" to "application/rss+xml",
        ".zip" to "application/zip",
        ".apk" to "application/vnd.android.package-archive",
        ".cdy" to "application/vnd.cinderella",
        ".stl" to "application/vnd.ms-pki.stl",
        ".doc" to "application/msword",
        ".docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ".xls" to "application/vnd.ms-excel application/x-excel",
        ".xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ".pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        ".ppsx" to "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
        ".odb" to "application/vnd.oasis.opendocument.database",
        ".odf" to "application/vnd.oasis.opendocument.formula",
        ".odg" to "application/vnd.oasis.opendocument.graphics",
        ".otg" to "application/vnd.oasis.opendocument.graphics-template",
        ".odi" to "application/vnd.oasis.opendocument.image",
        ".ods" to "application/vnd.oasis.opendocument.spreadsheet",
        ".ots" to "application/vnd.oasis.opendocument.spreadsheet-template",
        ".odt" to "application/vnd.oasis.opendocument.text",
        ".odm" to "application/vnd.oasis.opendocument.text-master",
        ".ott" to "application/vnd.oasis.opendocument.text-template",
        ".oth" to "application/vnd.oasis.opendocument.text-web",
        ".cod" to "application/vnd.rim.cod",
        ".mmf" to "application/vnd.smaf",
        ".sdc" to "application/vnd.stardivision.calc",
        ".sda" to "application/vnd.stardivision.draw",
        ".sdd" to "application/vnd.stardivision.impress",
        ".sdp" to "application/vnd.stardivision.impress",
        ".smf" to "application/vnd.stardivision.math",
        ".sdw" to "application/vnd.stardivision.writer",
        ".vor" to "application/vnd.stardivision.writer",
        ".sgl" to "application/vnd.stardivision.writer-global",
        ".sxc" to "application/vnd.sun.xml.calc",
        ".stc" to "application/vnd.sun.xml.calc.template",
        ".sxd" to "application/vnd.sun.xml.draw",
        ".std" to "application/vnd.sun.xml.draw.template",
        ".sxi" to "application/vnd.sun.xml.impress",
        ".sti" to "application/vnd.sun.xml.impress.template",
        ".sxm" to "application/vnd.sun.xml.math",
        ".sxw" to "application/vnd.sun.xml.writer",
        ".sxg" to "application/vnd.sun.xml.writer.global",
        ".stw" to "application/vnd.sun.xml.writer.template",
        ".vsd" to "application/vnd.visio",
        ".abw" to "application/x-abiword",
        ".dmg" to "application/x-apple-diskimage",
        ".bcpio" to "application/x-bcpio",
        ".torrent" to "application/x-bittorrent",
        ".cdf" to "application/x-cdf",
        ".vcd" to "application/x-cdlink",
        ".pgn" to "application/x-chess-pgn",
        ".cpio" to "application/x-cpio",
        ".deb" to "application/x-debian-package",
        ".udeb" to "application/x-debian-package",
        ".dcr" to "application/x-director",
        ".dir" to "application/x-director",
        ".dxr" to "application/x-director",
        ".dms" to "application/x-dms",
        ".wad" to "application/x-doom",
        ".dvi" to "application/x-dvi",
        ".flac" to "application/x-flac",
        ".pfa" to "application/x-font",
        ".pfb" to "application/x-font",
        ".gsf" to "application/x-font",
        ".pcf" to "application/x-font",
        ".pcf.Z" to "application/x-font",
        ".mm" to "application/x-freemind",
        ".spl" to "application/x-futuresplash",
        ".gnumeric" to "application/x-gnumeric",
        ".sgf" to "application/x-go-sgf",
        ".gcf" to "application/x-graphing-calculator",
        ".gtar" to "application/x-gtar",
        ".tgz" to "application/x-gtar",
        ".taz" to "application/x-gtar",
        ".hdf" to "application/x-hdf",
        ".ica" to "application/x-ica",
        ".ins" to "application/x-internet-signup",
        ".isp" to "application/x-internet-signup",
        ".iii" to "application/x-iphone",
        ".iso" to "application/x-iso9660-image",
        ".jmz" to "application/x-jmol",
        ".chrt" to "application/x-kchart",
        ".kil" to "application/x-killustrator",
        ".skp" to "application/x-koan",
        ".skd" to "application/x-koan",
        ".skt" to "application/x-koan",
        ".skm" to "application/x-koan",
        ".kpr" to "application/x-kpresenter",
        ".kpt" to "application/x-kpresenter",
        ".ksp" to "application/x-kspread",
        ".kwd" to "application/x-kword",
        ".kwt" to "application/x-kword",
        ".latex" to "application/x-latex",
        ".lha" to "application/x-lha",
        ".lzh" to "application/x-lzh",
        ".lzx" to "application/x-lzx",
        ".frm" to "application/x-maker",
        ".maker" to "application/x-maker",
        ".frame" to "application/x-maker",
        ".fb" to "application/x-maker",
        ".book" to "application/x-maker",
        ".fbdoc" to "application/x-maker",
        ".mif" to "application/x-mif",
        ".wmd" to "application/x-ms-wmd",
        ".wmz" to "application/x-ms-wmz",
        ".msi" to "application/x-msi",
        ".pac" to "application/x-ns-proxy-autoconfig",
        ".nwc" to "application/x-nwc",
        ".o" to "application/x-object",
        ".oza" to "application/x-oz-application",
        ".p7r" to "application/x-pkcs7-certreqresp",
        ".crl" to "application/x-pkcs7-crl",
        ".qtl" to "application/x-quicktimeplayer",
        ".shar" to "application/x-shar",
        ".sit" to "application/x-stuffit",
        ".sv4cpio" to "application/x-sv4cpio",
        ".sv4crc" to "application/x-sv4crc",
        ".tar" to "application/x-tar",
        ".texinfo" to "application/x-texinfo",
        ".texi" to "application/x-texinfo",
        ".t" to "application/x-troff",
        ".roff" to "application/x-troff",
        ".man" to "application/x-troff-man",
        ".ustar" to "application/x-ustar",
        ".src" to "application/x-wais-source",
        ".wz" to "application/x-wingz",
        ".webarchive" to "application/x-webarchive",
        ".crt" to "application/x-x509-ca-cert",
        ".xcf" to "application/x-xcf",
        ".fig" to "application/x-xfig",
        ".snd" to "audio/basic",
        ".mid" to "audio/midi",
        ".midi" to "audio/midi",
        ".kar" to "audio/midi",
        ".mpga" to "audio/mpeg",
        ".mpega" to "audio/mpeg",
        ".mp2" to "audio/mpeg",
        ".mp3" to "audio/mpeg",
        ".m4a" to "audio/mpeg",
        ".m3u" to "audio/mpegurl",
        ".sid" to "audio/prs.sid",
        ".aif" to "audio/x-aiff",
        ".aiff" to "audio/x-aiff",
        ".aifc" to "audio/x-aiff",
        ".gsm" to "audio/x-gsm",
        ".m3u" to "audio/x-mpegurl",
        ".wma" to "audio/x-ms-wma",
        ".wax" to "audio/x-ms-wax",
        ".ra" to "audio/x-pn-realaudio",
        ".rm" to "audio/x-pn-realaudio",
        ".ram" to "audio/x-pn-realaudio",
        ".ra" to "audio/x-realaudio",
        ".pls" to "audio/x-scpls",
        ".sd2" to "audio/x-sd2",
        ".wav" to "audio/x-wav",
        ".bmp" to "image/bmp",
        ".gif" to "image/gif",
        ".cur" to "image/ico",
        ".ico" to "image/ico",
        ".ief" to "image/ief",
        ".jpeg" to "image/jpeg",
        ".jpg" to "image/jpeg",
        ".jpe" to "image/jpeg",
        ".pcx" to "image/pcx",
        ".png" to "image/png",
        ".svg" to "image/svg+xml",
        ".svgz" to "image/svg+xml",
        ".tiff" to "image/tiff",
        ".tif" to "image/tiff",
        ".djvu" to "image/vnd.djvu",
        ".djv" to "image/vnd.djvu",
        ".wbmp" to "image/vnd.wap.wbmp",
        ".ras" to "image/x-cmu-raster",
        ".cdr" to "image/x-coreldraw",
        ".pat" to "image/x-coreldrawpattern",
        ".cdt" to "image/x-coreldrawtemplate",
        ".cpt" to "image/x-corelphotopaint",
        ".ico" to "image/x-icon",
        ".art" to "image/x-jg",
        ".jng" to "image/x-jng",
        ".bmp" to "image/x-ms-bmp",
        ".psd" to "image/x-photoshop",
        ".pnm" to "image/x-portable-anymap",
        ".pbm" to "image/x-portable-bitmap",
        ".pgm" to "image/x-portable-graymap",
        ".ppm" to "image/x-portable-pixmap",
        ".rgb" to "image/x-rgb",
        ".xbm" to "image/x-xbitmap",
        ".xpm" to "image/x-xpixmap",
        ".xwd" to "image/x-xwindowdump",
        ".igs" to "model/iges",
        ".iges" to "model/iges",
        ".msh" to "model/mesh",
        ".mesh" to "model/mesh",
        ".silo" to "model/mesh",
        ".ics" to "text/calendar",
        ".icz" to "text/calendar",
        ".csv" to "text/comma-separated-values",
        ".css" to "text/css",
        ".323" to "text/h323",
        ".uls" to "text/iuls",
        ".mml" to "text/mathml",
        ".txt" to "text/plain",
        ".asc" to "text/plain",
        ".text" to "text/plain",
        ".diff" to "text/plain",
        ".pot" to "text/plain",
        ".html" to "text/html",
        ".js" to "text/javascript",
        ".xml" to "text/xml",
        ".rtx" to "text/richtext",
        ".rtf" to "text/rtf",
        ".ts" to "text/texmacs",
        ".phps" to "text/text",
        ".tsv" to "text/tab-separated-values",
        ".bib" to "text/x-bibtex",
        ".boo" to "text/x-boo",
        ".h++" to "text/x-c++hdr",
        ".hpp" to "text/x-c++hdr",
        ".hxx" to "text/x-c++hdr",
        ".hh" to "text/x-c++hdr",
        ".c++" to "text/x-c++src",
        ".cpp" to "text/x-c++src",
        ".cxx" to "text/x-c++src",
        ".h" to "text/x-chdr",
        ".htc" to "text/x-component",
        ".csh" to "text/x-csh",
        ".c" to "text/x-csrc",
        ".d" to "text/x-dsrc",
        ".hs" to "text/x-haskell",
        ".java" to "text/x-java",
        ".lhs" to "text/x-literate-haskell",
        ".moc" to "text/x-moc",
        ".p" to "text/x-pascal",
        ".pas" to "text/x-pascal",
        ".gcd" to "text/x-pcs-gcd",
        ".etx" to "text/x-setext",
        ".tcl" to "text/x-tcl",
        ".tex" to "text/x-tex",
        ".ltx" to "text/x-tex",
        ".sty" to "text/x-tex",
        ".cls" to "text/x-tex",
        ".vcs" to "text/x-vcalendar",
        ".vcf" to "text/x-vcard",
        ".3gp" to "video/3gpp",
        ".3g2" to "video/3gpp",
        ".dl" to "video/dl",
        ".dif" to "video/dv",
        ".dv" to "video/dv",
        ".fli" to "video/fli",
        ".mpeg" to "video/mpeg",
        ".mpg" to "video/mpeg",
        ".mpe" to "video/mpeg",
        ".mp4" to "video/mp4",
        ".VOB" to "video/mpeg",
        ".qt" to "video/quicktime",
        ".mov" to "video/quicktime",
        ".mxu" to "video/vnd.mpegurl",
        ".lsf" to "video/x-la-asf",
        ".lsx" to "video/x-la-asf",
        ".mng" to "video/x-mng",
        ".asf" to "video/x-ms-asf",
        ".asx" to "video/x-ms-asf",
        ".wm" to "video/x-ms-wm",
        ".wmv" to "video/x-ms-wmv",
        ".wmx" to "video/x-ms-wmx",
        ".wvx" to "video/x-ms-wvx",
        ".avi" to "video/x-msvideo",
        ".movie" to "video/x-sgi-movie",
        ".ice" to "x-conference/x-cooltalk",
        ".sisx " to "x-epoc/x-sisx-app"
    )

    /**
     * 根据文件MimeType获取扩展名
     */
    fun getExtensionFromMimeType(mimeType: String?): String? {
        val b = mimeTypeAndSuffix.containsKey(mimeType)
        return if (b) {
            mimeTypeAndSuffix[mimeType]
        } else null
    }

    /**
     * 根据文件uri获取扩展名
     */
    fun getExtension(uri: String): String? {
        return getExtensionFromMimeType(getMiniType(uri))
    }

    /**
     * 根据File获取扩展名
     */
    fun getExtension(file: File): String? {
        return getExtensionFromMimeType(getMiniType(file))
    }

    /**
     * 获取文件MimeType
     */
    fun getMiniType(uri: Uri): String? {
        return getMiniType(uri.toString())
    }

    /**
     * 获取文件MimeType
     */
    fun getMiniType(file: File): String? {
        return getMiniType(file.toString())
    }

    /**
     * 获取文件MimeType
     */
    fun getMiniType(uri: String): String? {
        var mimeType: String? = null
        suffixAntMiniType.keys.forEach {
            if (uri.endsWith(it)) {
                mimeType = suffixAntMiniType[it]
            }
        }
        return mimeType
    }

}